<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>OptionalValues.Mvc</PackageId>
    <Description>MVC validation metadata support for OptionalValues.</Description>
    <PackageTags>$(CommonPackageTags) aspnetcore mvc validation</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\OptionalValues\OptionalValues.csproj" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

</Project>
