openapi: 3.0.0
info:
  title: OptionalValues.Examples.NSwag
  version: 1.0.0
paths:
  /company:
    post:
      tags:
      - Example
      operationId: Example Post
      requestBody:
        x-name: company
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Company'
        required: true
        x-position: 1
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Company'
components:
  schemas:
    Company:
      type: object
      additionalProperties: false
      required:
      - name
      properties:
        id:
          type: string
          format: guid
        name:
          type: string
        summary:
          type: string
          nullable: true
        contact:
          $ref: '#/components/schemas/Person'
    Person:
      type: object
      additionalProperties: false
      properties:
        name:
          type: string
          nullable: true
        age:
          type: integer
          format: int32
          maximum: 120
          minimum: 0
        address:
          $ref: '#/components/schemas/Address'
    Address:
      type: object
      additionalProperties: false
      properties:
        street:
          type: string
        city:
          type: string
        state:
          type: string
          pattern: ^[a-zA-Z ]+$
        zip:
          type: string
          nullable: true
